.TH "tests/check_vstring.c" 3 "Tue Oct 17 2017" "Version 0.1" "vString" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/check_vstring.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <check\&.h>\fP
.br
\fC#include '\&.\&./src/vstring\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAPACITY\fP   1000"
.br
.ti -1c
.RI "#define \fBN\fP   5000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSTART_TEST\fP (vstring)"
.br
.ti -1c
.RI "END_TEST Suite * \fBvstring_suite\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAPACITY   1000"

.SS "#define N   5000"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "START_TEST (vstring)"

.SS "END_TEST Suite* vstring_suite ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for vString from the source code\&.
