.TH "src/from_file.c" 3 "Tue Oct 17 2017" "Version 0.1" "vString" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/from_file.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'vstring\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAPACITY\fP   1024"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAPACITY   1024"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for vString from the source code\&.
